// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqn6ZJvG4v78uSA43Sffm_nIfnmTPB6Bg',
    appId: '1:906752927081:web:c433213112932cef4d49f8',
    messagingSenderId: '906752927081',
    projectId: 'proyecto-capibara',
    authDomain: 'proyecto-capibara.firebaseapp.com',
    storageBucket: 'proyecto-capibara.firebasestorage.app',
    measurementId: 'G-MP184CQG6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhWjfHyu94C1T4WQPmNaG9B9q7HduMy8Q',
    appId: '1:906752927081:android:9950c4a546e2061f4d49f8',
    messagingSenderId: '906752927081',
    projectId: 'proyecto-capibara',
    storageBucket: 'proyecto-capibara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtaxeXowk-gnZc7wVYhfGSJaLlcYBHjl8',
    appId: '1:906752927081:ios:58ada893d8d877ed4d49f8',
    messagingSenderId: '906752927081',
    projectId: 'proyecto-capibara',
    storageBucket: 'proyecto-capibara.firebasestorage.app',
    iosBundleId: 'com.example.ilearnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtaxeXowk-gnZc7wVYhfGSJaLlcYBHjl8',
    appId: '1:906752927081:ios:58ada893d8d877ed4d49f8',
    messagingSenderId: '906752927081',
    projectId: 'proyecto-capibara',
    storageBucket: 'proyecto-capibara.firebasestorage.app',
    iosBundleId: 'com.example.ilearnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqn6ZJvG4v78uSA43Sffm_nIfnmTPB6Bg',
    appId: '1:906752927081:web:20a734aa5a2a28d24d49f8',
    messagingSenderId: '906752927081',
    projectId: 'proyecto-capibara',
    authDomain: 'proyecto-capibara.firebaseapp.com',
    storageBucket: 'proyecto-capibara.firebasestorage.app',
    measurementId: 'G-9RYSNY65GB',
  );
}
