name: ilearn_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.14.0
  firebase_core: ^2.32.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_markdown: ^0.6.18

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo-06.png
    - assets/images/capi_profesor.png
    - assets/images/Capi-tortuga.png
    - assets/images/capi_scientist.png
    - assets/images/capi_gamer.png
    - assets/images/capi_super_hero.png
    - assets/images/capi_idea.png
    - assets/images/capi_checklist.png
    - assets/images/capi_tender.png
    - assets/images/lightbulb.png
    - assets/images/progress.png
    - assets/images/vinculate.png
    - assets/images/fondo_night.png
    - assets/images/fondo_bright.png
    - assets/curriculum/math_5_b.txt
    - assets/images/capi_aventurero_2.png
    - assets/images/pizza_full.png
